# Generated by Django 5.2.1 on 2026-06-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sabor',
                'verbose_name_plural': 'Sabores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_g', models.IntegerField(unique=True)),
                ('rotulo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
                'ordering': ['peso_g'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dose_g', models.IntegerField(default=30)),
                ('proteina_g', models.DecimalField(decimal_places=1, max_digits=5)),
                ('url_afiliado', models.URLField()),
                ('url_imagem', models.URLField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalog.marca')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalog.plataforma')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalog.sabor')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalog.tamanho')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['preco'],
            },
        ),
    ]
