# Generated by Django 5.2.1 on 2026-06-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='url_produto',
            field=models.URLField(blank=True, help_text='Link limpo do produto (usado para atualizar preços)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='url_afiliado',
            field=models.URLField(blank=True, help_text='Link de afiliado exibido pro usuário'),
        ),
    ]
