# Generated by Django 5.2.1 on 2026-09-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_mltoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Desmarcado automaticamente quando o ML não tem mais oferta; oculto do site'),
        ),
    ]
